# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 01:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('domain', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('exported', models.DateTimeField()),
                ('rrs', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('see_all', "Can see all users' domains"),),
            },
        ),
    ]
